name: CodeBuild runners hosted on AWS

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        environment:
          - bedrock
          - ag

    environment: ${{ matrix.environment }}
    concurrency: ${{ matrix.environment }}

    runs-on: codebuild-infrastructure-test-role-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      # This might not be necessary when it runs on an actual workflow, only required on local actions which is this case
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v1
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Dive into tenant
        shell: bash
        run: cd ${{ vars.FOLDER_PATH }} && terraform init && terraform plan
      - name: What is my session name
        shell: sh
        run: aws sts get-caller-identity
